In [1]:
import os
import pandas as pd
import numpy as np

path = 'test_results/BCICompet2a'

In [3]:
results = os.listdir(path)
results = [element for element in results if 'all_' not in element]

In [12]:

columns = ['Subject', 'Accuracy', 'Kappa']
dfs = [pd.read_csv(os.path.join(path, result)) for result in results]
for df in dfs:
    df.columns = columns
for i in range(len(dfs)):
    dfs[i]['method'] = results[i].split('-')[-2].split('.')[0]
concat_df = pd.concat(dfs)

In [13]:

# Create Accuracy DataFrame
accuracy_df = concat_df.pivot(index='Subject', columns='method', values='Accuracy')

# Create Kappa DataFrame
kappa_df = concat_df.pivot(index='Subject', columns='method', values='Kappa')

In [16]:
# Calculate mean and standard deviation for Accuracy and Kappa
accuracy_mean = accuracy_df.mean()
accuracy_std = accuracy_df.std()
kappa_mean = kappa_df.mean()
kappa_std = kappa_df.std()

# Append mean and standard deviation to the DataFrames
accuracy_df.loc['Mean'] = accuracy_mean
accuracy_df.loc['Std'] = accuracy_std
kappa_df.loc['Mean'] = kappa_mean
kappa_df.loc['Std'] = kappa_std

In [17]:
accuracy_df

method       attn       avg  baseline       cat       ftr
Subject
0        0.812500  0.815972  0.791667  0.777778  0.843750
1        0.482639  0.503472  0.489583  0.506944  0.506944
2        0.868056  0.878472  0.885417  0.871528  0.895833
3        0.701389  0.694444  0.708333  0.715278  0.708333
4        0.645833  0.690972  0.659722  0.677083  0.652778
5        0.579861  0.635417  0.579861  0.618056  0.625000
6        0.829861  0.847222  0.802083  0.795139  0.826389
7        0.819444  0.802083  0.826389  0.857639  0.840278
8        0.760417  0.760417  0.722222  0.756944  0.763889
Mean     0.722222  0.736497  0.718364  0.730710  0.740355
Std      0.130312  0.118304  0.126014  0.116657  0.127125

In [18]:
kappa_df

method       attn       avg  baseline       cat       ftr
Subject
0        0.750000  0.754630  0.722222  0.703704  0.791667
1        0.310185  0.337963  0.319444  0.342593  0.342593
2        0.824074  0.837963  0.847222  0.828704  0.861111
3        0.601852  0.592593  0.611111  0.620370  0.611111
4        0.527778  0.587963  0.546296  0.569444  0.537037
5        0.439815  0.513889  0.439815  0.490741  0.500000
6        0.773148  0.796296  0.736111  0.726852  0.768519
7        0.759259  0.736111  0.768519  0.810185  0.787037
8        0.680556  0.680556  0.629630  0.675926  0.685185
Mean     0.629630  0.648663  0.624486  0.640947  0.653807
Std      0.173750  0.157738  0.168019  0.155543  0.169500